# Generated by Django 4.2.1 on 2023-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_hashtag_comment_blog_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="blog_photo"),
        ),
    ]
